version: '3'

services:
  backend:
    environment:
      - HOST=0.0.0.0
      - PORT=8080
    ports:
      - "8080:8080"
    build:
      context: ./backend
      dockerfile: Dockerfile.back
  frontend:
    environment:
      - PORT=8081
    ports:
      - "8081:8081"
    build:
      context: ./frontend
      dockerfile: Dockerfile.front
