version: '3'

services:
  backend:
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    build:
      context: ./backend
      dockerfile: Dockerfile.back
  frontend:
    environment:
      - PORT=8081
      - REACT_APP_SERVER_URL=http://localhost:8080
    ports:
      - "8081:8081"
    build:
      context: ./frontend
      dockerfile: Dockerfile.front
